# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'uiFile/color_calibrator.ui'
#
# Created by: PyQt4 UI code generator 4.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_ColorCalibrator(object):
    def setupUi(self, ColorCalibrator):
        ColorCalibrator.setObjectName(_fromUtf8("ColorCalibrator"))
        ColorCalibrator.resize(1021, 905)
        self.centralwidget = QtGui.QWidget(ColorCalibrator)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.HLow = QtGui.QSlider(self.centralwidget)
        self.HLow.setGeometry(QtCore.QRect(180, 700, 160, 16))
        self.HLow.setMaximum(255)
        self.HLow.setOrientation(QtCore.Qt.Horizontal)
        self.HLow.setObjectName(_fromUtf8("HLow"))
        self.SLow = QtGui.QSlider(self.centralwidget)
        self.SLow.setGeometry(QtCore.QRect(180, 730, 160, 16))
        self.SLow.setMaximum(255)
        self.SLow.setOrientation(QtCore.Qt.Horizontal)
        self.SLow.setObjectName(_fromUtf8("SLow"))
        self.VLow = QtGui.QSlider(self.centralwidget)
        self.VLow.setGeometry(QtCore.QRect(180, 760, 160, 16))
        self.VLow.setMaximum(255)
        self.VLow.setOrientation(QtCore.Qt.Horizontal)
        self.VLow.setObjectName(_fromUtf8("VLow"))
        self.HUpper = QtGui.QSlider(self.centralwidget)
        self.HUpper.setGeometry(QtCore.QRect(420, 700, 160, 16))
        self.HUpper.setMaximum(255)
        self.HUpper.setOrientation(QtCore.Qt.Horizontal)
        self.HUpper.setObjectName(_fromUtf8("HUpper"))
        self.SUpper = QtGui.QSlider(self.centralwidget)
        self.SUpper.setGeometry(QtCore.QRect(420, 730, 160, 16))
        self.SUpper.setMaximum(255)
        self.SUpper.setOrientation(QtCore.Qt.Horizontal)
        self.SUpper.setObjectName(_fromUtf8("SUpper"))
        self.VUpper = QtGui.QSlider(self.centralwidget)
        self.VUpper.setGeometry(QtCore.QRect(420, 760, 160, 16))
        self.VUpper.setMaximum(255)
        self.VUpper.setOrientation(QtCore.Qt.Horizontal)
        self.VUpper.setObjectName(_fromUtf8("VUpper"))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(140, 700, 21, 16))
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(140, 730, 21, 16))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_3 = QtGui.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(140, 760, 21, 16))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_4 = QtGui.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(240, 670, 67, 17))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_5 = QtGui.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(480, 670, 67, 17))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.cameraComboBox = QtGui.QComboBox(self.centralwidget)
        self.cameraComboBox.setGeometry(QtCore.QRect(120, 10, 161, 21))
        self.cameraComboBox.setObjectName(_fromUtf8("cameraComboBox"))
        self.cameraComboBox.addItem(_fromUtf8(""))
        self.cameraComboBox.addItem(_fromUtf8(""))
        self.label_6 = QtGui.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(20, 10, 91, 21))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.label_7 = QtGui.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(20, 50, 111, 21))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.pushButton = QtGui.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(140, 50, 89, 25))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.cameraButton = QtGui.QPushButton(self.centralwidget)
        self.cameraButton.setGeometry(QtCore.QRect(290, 10, 89, 25))
        self.cameraButton.setObjectName(_fromUtf8("cameraButton"))
        self.label_8 = QtGui.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(20, 90, 101, 21))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.namefileEdit = QtGui.QLineEdit(self.centralwidget)
        self.namefileEdit.setGeometry(QtCore.QRect(120, 90, 113, 25))
        self.namefileEdit.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.namefileEdit.setObjectName(_fromUtf8("namefileEdit"))
        self.saveButton = QtGui.QPushButton(self.centralwidget)
        self.saveButton.setGeometry(QtCore.QRect(250, 90, 89, 25))
        self.saveButton.setObjectName(_fromUtf8("saveButton"))
        self.frame = QtGui.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(80, 650, 561, 151))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.label_9 = QtGui.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(80, 620, 111, 21))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.imageLable = QtGui.QLabel(self.centralwidget)
        self.imageLable.setGeometry(QtCore.QRect(40, 130, 640, 480))
        self.imageLable.setFrameShape(QtGui.QFrame.Panel)
        self.imageLable.setText(_fromUtf8(""))
        self.imageLable.setObjectName(_fromUtf8("imageLable"))
        self.colorComboBox = QtGui.QComboBox(self.centralwidget)
        self.colorComboBox.setGeometry(QtCore.QRect(470, 90, 86, 25))
        self.colorComboBox.setObjectName(_fromUtf8("colorComboBox"))
        self.colorComboBox.addItem(_fromUtf8(""))
        self.colorComboBox.addItem(_fromUtf8(""))
        self.label_10 = QtGui.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(370, 90, 91, 21))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.GreenHLow = QtGui.QLabel(self.centralwidget)
        self.GreenHLow.setGeometry(QtCore.QRect(770, 220, 67, 17))
        self.GreenHLow.setFrameShape(QtGui.QFrame.Box)
        self.GreenHLow.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.GreenHLow.setObjectName(_fromUtf8("GreenHLow"))
        self.GreenSLow = QtGui.QLabel(self.centralwidget)
        self.GreenSLow.setGeometry(QtCore.QRect(850, 220, 67, 17))
        self.GreenSLow.setFrameShape(QtGui.QFrame.Box)
        self.GreenSLow.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.GreenSLow.setObjectName(_fromUtf8("GreenSLow"))
        self.GreenVLow = QtGui.QLabel(self.centralwidget)
        self.GreenVLow.setGeometry(QtCore.QRect(930, 220, 67, 17))
        self.GreenVLow.setFrameShape(QtGui.QFrame.Box)
        self.GreenVLow.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.GreenVLow.setObjectName(_fromUtf8("GreenVLow"))
        self.GreenHUpper = QtGui.QLabel(self.centralwidget)
        self.GreenHUpper.setGeometry(QtCore.QRect(770, 280, 67, 17))
        self.GreenHUpper.setFrameShape(QtGui.QFrame.Box)
        self.GreenHUpper.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.GreenHUpper.setObjectName(_fromUtf8("GreenHUpper"))
        self.GreenSUpper = QtGui.QLabel(self.centralwidget)
        self.GreenSUpper.setGeometry(QtCore.QRect(850, 280, 67, 17))
        self.GreenSUpper.setFrameShape(QtGui.QFrame.Box)
        self.GreenSUpper.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.GreenSUpper.setObjectName(_fromUtf8("GreenSUpper"))
        self.GreenVUpper = QtGui.QLabel(self.centralwidget)
        self.GreenVUpper.setGeometry(QtCore.QRect(930, 280, 67, 17))
        self.GreenVUpper.setFrameShape(QtGui.QFrame.Box)
        self.GreenVUpper.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.GreenVUpper.setObjectName(_fromUtf8("GreenVUpper"))
        self.label_17 = QtGui.QLabel(self.centralwidget)
        self.label_17.setGeometry(QtCore.QRect(860, 170, 41, 17))
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.label_19 = QtGui.QLabel(self.centralwidget)
        self.label_19.setGeometry(QtCore.QRect(860, 350, 61, 17))
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.OrangeSUpper = QtGui.QLabel(self.centralwidget)
        self.OrangeSUpper.setGeometry(QtCore.QRect(850, 460, 67, 17))
        self.OrangeSUpper.setFrameShape(QtGui.QFrame.Box)
        self.OrangeSUpper.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.OrangeSUpper.setObjectName(_fromUtf8("OrangeSUpper"))
        self.OrangeHLow = QtGui.QLabel(self.centralwidget)
        self.OrangeHLow.setGeometry(QtCore.QRect(770, 400, 67, 17))
        self.OrangeHLow.setFrameShape(QtGui.QFrame.Box)
        self.OrangeHLow.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.OrangeHLow.setObjectName(_fromUtf8("OrangeHLow"))
        self.OrangeSLow = QtGui.QLabel(self.centralwidget)
        self.OrangeSLow.setGeometry(QtCore.QRect(850, 400, 67, 17))
        self.OrangeSLow.setFrameShape(QtGui.QFrame.Box)
        self.OrangeSLow.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.OrangeSLow.setObjectName(_fromUtf8("OrangeSLow"))
        self.OrangeVUpper = QtGui.QLabel(self.centralwidget)
        self.OrangeVUpper.setGeometry(QtCore.QRect(930, 460, 67, 17))
        self.OrangeVUpper.setFrameShape(QtGui.QFrame.Box)
        self.OrangeVUpper.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.OrangeVUpper.setObjectName(_fromUtf8("OrangeVUpper"))
        self.OrangeHUpper = QtGui.QLabel(self.centralwidget)
        self.OrangeHUpper.setGeometry(QtCore.QRect(770, 460, 67, 17))
        self.OrangeHUpper.setFrameShape(QtGui.QFrame.Box)
        self.OrangeHUpper.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.OrangeHUpper.setObjectName(_fromUtf8("OrangeHUpper"))
        self.OrangeVLow = QtGui.QLabel(self.centralwidget)
        self.OrangeVLow.setGeometry(QtCore.QRect(930, 400, 67, 17))
        self.OrangeVLow.setFrameShape(QtGui.QFrame.Box)
        self.OrangeVLow.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.OrangeVLow.setObjectName(_fromUtf8("OrangeVLow"))
        self.ChangeButton = QtGui.QPushButton(self.centralwidget)
        self.ChangeButton.setGeometry(QtCore.QRect(320, 820, 89, 25))
        self.ChangeButton.setObjectName(_fromUtf8("ChangeButton"))
        self.label_11 = QtGui.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(770, 200, 67, 17))
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.label_12 = QtGui.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(770, 380, 67, 17))
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.label_13 = QtGui.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(770, 440, 67, 17))
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.label_14 = QtGui.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(770, 260, 67, 17))
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.label_15 = QtGui.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(850, 200, 67, 17))
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.label_16 = QtGui.QLabel(self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(850, 440, 67, 17))
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.label_18 = QtGui.QLabel(self.centralwidget)
        self.label_18.setGeometry(QtCore.QRect(850, 260, 67, 17))
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.label_20 = QtGui.QLabel(self.centralwidget)
        self.label_20.setGeometry(QtCore.QRect(850, 380, 67, 17))
        self.label_20.setAlignment(QtCore.Qt.AlignCenter)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.label_21 = QtGui.QLabel(self.centralwidget)
        self.label_21.setGeometry(QtCore.QRect(930, 380, 67, 17))
        self.label_21.setAlignment(QtCore.Qt.AlignCenter)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.label_22 = QtGui.QLabel(self.centralwidget)
        self.label_22.setGeometry(QtCore.QRect(930, 200, 67, 17))
        self.label_22.setAlignment(QtCore.Qt.AlignCenter)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.label_23 = QtGui.QLabel(self.centralwidget)
        self.label_23.setGeometry(QtCore.QRect(930, 440, 67, 17))
        self.label_23.setAlignment(QtCore.Qt.AlignCenter)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.label_24 = QtGui.QLabel(self.centralwidget)
        self.label_24.setGeometry(QtCore.QRect(930, 260, 67, 17))
        self.label_24.setAlignment(QtCore.Qt.AlignCenter)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.label_25 = QtGui.QLabel(self.centralwidget)
        self.label_25.setGeometry(QtCore.QRect(690, 220, 67, 17))
        self.label_25.setAlignment(QtCore.Qt.AlignCenter)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.label_26 = QtGui.QLabel(self.centralwidget)
        self.label_26.setGeometry(QtCore.QRect(690, 280, 67, 17))
        self.label_26.setAlignment(QtCore.Qt.AlignCenter)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.label_27 = QtGui.QLabel(self.centralwidget)
        self.label_27.setGeometry(QtCore.QRect(690, 460, 67, 17))
        self.label_27.setAlignment(QtCore.Qt.AlignCenter)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.label_28 = QtGui.QLabel(self.centralwidget)
        self.label_28.setGeometry(QtCore.QRect(690, 400, 67, 17))
        self.label_28.setAlignment(QtCore.Qt.AlignCenter)
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.verticalLayoutWidget = QtGui.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(690, 130, 321, 361))
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.frame.raise_()
        self.HLow.raise_()
        self.SLow.raise_()
        self.VLow.raise_()
        self.HUpper.raise_()
        self.SUpper.raise_()
        self.VUpper.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.label_4.raise_()
        self.label_5.raise_()
        self.cameraComboBox.raise_()
        self.label_6.raise_()
        self.label_7.raise_()
        self.pushButton.raise_()
        self.cameraButton.raise_()
        self.label_8.raise_()
        self.namefileEdit.raise_()
        self.saveButton.raise_()
        self.label_9.raise_()
        self.imageLable.raise_()
        self.colorComboBox.raise_()
        self.label_10.raise_()
        self.GreenHLow.raise_()
        self.GreenSLow.raise_()
        self.GreenVLow.raise_()
        self.GreenHUpper.raise_()
        self.GreenSUpper.raise_()
        self.GreenVUpper.raise_()
        self.label_17.raise_()
        self.label_19.raise_()
        self.OrangeSUpper.raise_()
        self.OrangeHLow.raise_()
        self.OrangeSLow.raise_()
        self.OrangeVUpper.raise_()
        self.OrangeHUpper.raise_()
        self.OrangeVLow.raise_()
        self.ChangeButton.raise_()
        self.label_11.raise_()
        self.label_12.raise_()
        self.label_13.raise_()
        self.label_14.raise_()
        self.label_15.raise_()
        self.label_16.raise_()
        self.label_18.raise_()
        self.label_20.raise_()
        self.label_21.raise_()
        self.label_22.raise_()
        self.label_23.raise_()
        self.label_24.raise_()
        self.label_25.raise_()
        self.label_26.raise_()
        self.label_27.raise_()
        self.label_28.raise_()
        self.verticalLayoutWidget.raise_()
        ColorCalibrator.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(ColorCalibrator)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1021, 22))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuColorCalibrator = QtGui.QMenu(self.menubar)
        self.menuColorCalibrator.setObjectName(_fromUtf8("menuColorCalibrator"))
        ColorCalibrator.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(ColorCalibrator)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        ColorCalibrator.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuColorCalibrator.menuAction())

        self.retranslateUi(ColorCalibrator)
        QtCore.QMetaObject.connectSlotsByName(ColorCalibrator)

    def retranslateUi(self, ColorCalibrator):
        ColorCalibrator.setWindowTitle(_translate("ColorCalibrator", "MainWindow", None))
        self.label.setText(_translate("ColorCalibrator", "H", None))
        self.label_2.setText(_translate("ColorCalibrator", "S", None))
        self.label_3.setText(_translate("ColorCalibrator", "V", None))
        self.label_4.setText(_translate("ColorCalibrator", "Lower", None))
        self.label_5.setText(_translate("ColorCalibrator", "Upper", None))
        self.cameraComboBox.setItemText(0, _translate("ColorCalibrator", "Webcam", None))
        self.cameraComboBox.setItemText(1, _translate("ColorCalibrator", "ExternalCamera", None))
        self.label_6.setText(_translate("ColorCalibrator", "VideoDevice", None))
        self.label_7.setText(_translate("ColorCalibrator", "GetFile Config", None))
        self.pushButton.setText(_translate("ColorCalibrator", "Browse", None))
        self.cameraButton.setText(_translate("ColorCalibrator", "Open", None))
        self.label_8.setText(_translate("ColorCalibrator", "Save Config", None))
        self.namefileEdit.setText(_translate("ColorCalibrator", "name_file", None))
        self.saveButton.setText(_translate("ColorCalibrator", "Save", None))
        self.label_9.setText(_translate("ColorCalibrator", "HSV Calibrator", None))
        self.colorComboBox.setItemText(0, _translate("ColorCalibrator", "Green", None))
        self.colorComboBox.setItemText(1, _translate("ColorCalibrator", "Orange", None))
        self.label_10.setText(_translate("ColorCalibrator", "Select Color", None))
        self.GreenHLow.setText(_translate("ColorCalibrator", "0", None))
        self.GreenSLow.setText(_translate("ColorCalibrator", "0", None))
        self.GreenVLow.setText(_translate("ColorCalibrator", "0", None))
        self.GreenHUpper.setText(_translate("ColorCalibrator", "0", None))
        self.GreenSUpper.setText(_translate("ColorCalibrator", "0", None))
        self.GreenVUpper.setText(_translate("ColorCalibrator", "0", None))
        self.label_17.setText(_translate("ColorCalibrator", "Green", None))
        self.label_19.setText(_translate("ColorCalibrator", "Orange", None))
        self.OrangeSUpper.setText(_translate("ColorCalibrator", "0", None))
        self.OrangeHLow.setText(_translate("ColorCalibrator", "0", None))
        self.OrangeSLow.setText(_translate("ColorCalibrator", "0", None))
        self.OrangeVUpper.setText(_translate("ColorCalibrator", "0", None))
        self.OrangeHUpper.setText(_translate("ColorCalibrator", "0", None))
        self.OrangeVLow.setText(_translate("ColorCalibrator", "0", None))
        self.ChangeButton.setText(_translate("ColorCalibrator", "Change !", None))
        self.label_11.setText(_translate("ColorCalibrator", "H", None))
        self.label_12.setText(_translate("ColorCalibrator", "H", None))
        self.label_13.setText(_translate("ColorCalibrator", "H", None))
        self.label_14.setText(_translate("ColorCalibrator", "H", None))
        self.label_15.setText(_translate("ColorCalibrator", "S", None))
        self.label_16.setText(_translate("ColorCalibrator", "S", None))
        self.label_18.setText(_translate("ColorCalibrator", "S", None))
        self.label_20.setText(_translate("ColorCalibrator", "S", None))
        self.label_21.setText(_translate("ColorCalibrator", "V", None))
        self.label_22.setText(_translate("ColorCalibrator", "V", None))
        self.label_23.setText(_translate("ColorCalibrator", "V", None))
        self.label_24.setText(_translate("ColorCalibrator", "V", None))
        self.label_25.setText(_translate("ColorCalibrator", "Lower", None))
        self.label_26.setText(_translate("ColorCalibrator", "Upper", None))
        self.label_27.setText(_translate("ColorCalibrator", "Upper", None))
        self.label_28.setText(_translate("ColorCalibrator", "Lower", None))
        self.menuColorCalibrator.setTitle(_translate("ColorCalibrator", "ColorCalibrator", None))

